- languages/en.json
- module.json
- scripts/modules/system-config.mjs
- scripts/setup.mjs
- styles/mythacri.css
Closes #1.
Closes #2.
Closes #3.
Closes #13.
Closes #23.
Closes #24.
Closes #25.
Closes #26.
Closes #27.
Closes #28.
> Initial setup and some minor config entries

- languages/en.json
- scripts/modules/data/crafting/base-crafting.mjs
- scripts/modules/system-config.mjs
- templates/parts/crafting-buttons.hbs
> Inject crafting buttons onto character sheets

- scripts/modules/applications/crafting-application.mjs
- scripts/modules/applications/recipe-sheet.mjs
- scripts/modules/data/crafting/base-crafting.mjs
Closes #58.
Closes #59.
Also fixed a few syntax issues that snuck in.
> [#58, #59]

- scripts/modules/system-config.mjs
- styles/mythacri.css
Closes #64
Closes #65
Removes electrum from the config, and thus also from actor sheets.
Fixed some css issue with soundboard.
Also cleaned up some minor things in the code.
> [#64, #65]

- styles/mythacri.css
> [#70] Remove resources on character sheets

- scripts/modules/data/concentration.mjs
- scripts/setup.mjs
> [#87] Witch concentration

- module.json
- scripts/modules/data/crafting.mjs
- scripts/modules/data/mayhem.mjs
- styles/mythacri.css
- templates/parts/long-rest.hbs
- templates/recipe-sheet.hbs
- Added 'Concentration Notifier' and 'Build-a-Bonus' as recommended modules in the manifest. This does not force them to be installed, but does prompt for it when enabling this module.
- Closes #89.
- Closes #90.
- Closes #92.
- Closes #93.
> Upkeep fixes

- scripts/modules/applications/crafting-application.mjs
- scripts/modules/applications/recipe-sheet.mjs
- scripts/modules/applications/runes-config.mjs
- scripts/modules/applications/soundboard.mjs
- scripts/modules/data/concentration.mjs
- scripts/modules/data/settings.mjs
- scripts/modules/interface.mjs
Some classes and methods were missing declarations. Also fixes #98.
> Amend some linting issues and missing comments

- scripts/modules/system-config.mjs
Added new weapon proficiencies from Valda's Spire of Secrets including basic firearms.
> [#18] New Weapon Proficiencies

- .github/workflows/main.yml
- module.json
After merging this, the steps to create a release are simply to make a release and tag it "v1.0.1" (bumping that number with each release). The 'v' is important.
The github action will add the `module.json` (updated with new version number and download location) and a `module.zip` automatically.
**Read and Write permissions for Github Actions in Settings of the repository are required.**
Closes #108.
> [#108] Create github action and update manifest

- languages/en.json
- scripts/modules/system-config.mjs
> [#118] Add 'Ranger Aspect' feature type

- languages/en.json
- scripts/modules/system-config.mjs
Adds new pepperbox and shield proficiencies (As best as we can)
Closes #120
Closes #140
> Shields n stuff

- scripts/modules/applications/storage-sheet.mjs
- scripts/modules/system-config.mjs
- styles/mythacri.css
Closes #150.
Closes #151.
Closes #152.
> [#150, #151, #152] Hotfix bugs

- scripts/modules/data/combat.mjs
> [#157] Add bounce animation hook

- module.json
- scripts/modules/data/combat.mjs
- scripts/modules/data/resting.mjs
- scripts/modules/data/token-auras.mjs
- scripts/modules/system-config.mjs
> [#164] Upkeep and fixes for v3.1.x

- scripts/modules/applications/storage-sheet.mjs
- Removed activation column.
- Added price column.
Closes #166.
> [#166] Storage sheet column changes

- languages/en.json
- module.json
- scripts/modules/data/models/behaviors.mjs
- scripts/setup.mjs
- templates/behavior-trap-message.hbs
> [#185] Implement trap region behavior

- languages/en.json
- scripts/modules/data/auras.mjs
This moves the aura functionality of Build-a-Bonus into this module.
> Move aura functionality entirely into module

- scripts/modules/applications/crafting-application.mjs
- scripts/modules/applications/recipe-sheet.mjs
- styles/mythacri.css
> [#207] Adjust css on alchemy crafting ui

- scripts/modules/data/configuration.mjs
> [#214] Fix mayhem action on npc sheets

- languages/en.json
- scripts/modules/applications/runes-config.mjs
- scripts/modules/data/crafting.mjs
- styles/mythacri.css
- templates/runes-config.hbs
> [#219] Implement new RunesConfig

- scripts/modules/applications/crafting-application.mjs
> [#218] Prevent assigning a component twice.
